apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: simple-app-destinationrule
spec:
  host: simple-app-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
